# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ce8c21029c1326ed10f89c3148e627634b9fe83dac8c03ef00d02a83e8d3546c0f6b7af5c57ecd11f2be835e5bb05d464460cef847f478cf7b00f58e8259e1ca

test:
  secret_key_base: ffe207fc835f47060f3bc0c0573084dbe61e4cc834b08fcd260a8a9792ec9ecf32ab8cf8e60dfafc19729f697273b2d743511bda674a02127e74e829d3e8a76b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
